services:
  ollama:
    stdin_open: true 
    tty: true  
    volumes:
        - ollama:/root/.ollama
    ports:
        - 11434:11434
    container_name: ollama-model
    image: ollama/ollama
    networks:
        - ollama-network

  ollamacli:
    depends_on:
      - ollama
    stdin_open: true # <--- THIS IS THE MISSING/INCORRECT LINE
    tty: true        # <--- THIS ONE IS CORRECTLY SET AS PER YOUR GREP
    image: ${DOCKER_REGISTRY-}ollamacli
    build:
      context: .
      dockerfile: OllamaCLI/Dockerfile
    networks:
      - ollama-network

volumes:
    ollama:
        name: ollama

networks:
    ollama-network:
      name: ollama-network
